version: '3.1'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "bankAccountManagementAdmin"
    ports:
    - "15432:5432"
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin"
      PGADMIN_DEFAULT_PASSWORD: "admin1234"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge