#############################################
#   CONFIGURATION
#############################################

# SERVER PORT
server:
  port: ${PORT}

# Actuator
management:
  context-path: /manage

# Datasource
spring:
  datasource:
    donus:
      jdbc-url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DEFAULT_SCHEMA}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

  liquibase:
    default-schema: ${DEFAULT_SCHEMA}